# Generated by Django 5.2.4 on 2025-07-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='TransmissionType',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
