# Generated by Django 5.2.4 on 2025-07-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number',
            field=models.CharField(default='Yoxdur', max_length=20),
        ),
    ]
